In [2]:
import numpy as np



In [6]:
# creating a 1-D numpy array
a=np.array([1,2,3,4,5])
b=np.array([5,7,8,9,10])
print(a,b)
print(type(a))
print(type(b))


[1 2 3 4 5] [ 5  7  8  9 10]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [9]:
print(a+b)
print(a*b)
print(a-b)

[ 6  9 11 13 15]
[ 5 14 24 36 50]
[-4 -5 -5 -5 -5]


np.array([ ],[ ],[ ])

In [14]:
n2=np.array([[1,2], [2,3]])
print(n2)

[[1 2]
 [2 3]]


In [16]:
n3=np.array([[2,3],[4,5],[6,7]])
print(n3)

[[2 3]
 [4 5]
 [6 7]]


In [22]:
print(n2.shape) # no. of rows and columns
print(n3.ndim)# no. of dimensions
print(n2.dtype) # data type of elements

(2, 2)
2
int32


In [24]:
np.arange(1,100,5)


array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [30]:
np.random.randint(1,10,size=(3,3))

array([[8, 9, 1],
       [5, 5, 2],
       [9, 9, 5]])

In [34]:

import os
os.cpu_count()

12

In [38]:
x=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
y=np.array([[1,5,3],
            [4,5,6],
            [7,3,9]])
            

In [41]:
print(x+y)
print(x@y) # matrix multiplication
print(np.dot(x,y)) # matrix multiplication

[[ 2  7  6]
 [ 8 10 12]
 [14 11 18]]
[[ 30  24  42]
 [ 66  63  96]
 [102 102 150]]
[[ 30  24  42]
 [ 66  63  96]
 [102 102 150]]


In [43]:
x.prod() # product of all elements in a matrix

362880

In [45]:
x.mean() # gives mean of all elements in the matrix

5.0

In [52]:
x.mean(axis=1)

array([2., 5., 8.])

In [53]:
x.std()
x.var()

6.666666666666667

In [51]:
print(x.min(axis=1))

[1 4 7]


In [61]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a,50))# median
print(np.percentile(a,25)) # 1 st quartile 
print(np.percentile(a,75)) # 3rd quartile

5.0
3.0
7.0


In [62]:
print(np.unique(x))

[1 2 3 4 5 6 7 8 9]


In [65]:
# reshaping 
a=np.random.randint(11,100,(4,4))
print(a)
print('2*8')
print(a.reshape(2,8))
print(a.reshape(2,2,4))


[[71 18 68 32]
 [84 66 61 35]
 [47 37 47 44]
 [93 56 15 63]]
2*8
[[71 18 68 32 84 66 61 35]
 [47 37 47 44 93 56 15 63]]
[[[71 18 68 32]
  [84 66 61 35]]

 [[47 37 47 44]
  [93 56 15 63]]]
